### ISSUE TITLE
Create way to remove/cleanup symlinks if steam protonfix is removed

### ISSUE THREAD

**Issue by marianoag** [Open-Wine-Components/ULWGL-protonfixes#1]
For easier maintenance and to automatically make any game from other store work (possibly even without being in the database) instead of adding a .py file with the steam protonfix path could it be that since we already have the steamid, instead of expecting a file if none is found the protonfix for steam store is used directly?

Also nitpicking now, if there's no entry in the database for other stores, the launcher using ULWGL could search the database for the title of the game and ask the user if it's the correct one or give them options to choose (of course that would depend on each app)

`#Set SteamGameId so that non-steam versions can pick up steam-specific fixes in proton's wine code
util.set_environment('SteamGameId','1174180')`

Is it to possibly to add this automatically in ULWGL-Launcher this seems that could be useful for many games and wouldn't need modifying the steam protonfix.

**Comment by GloriousEggroll** [comment]
No, we want a separate file for the game even if it's just a symlink pointing to the steam game id version. The reason is because in the event that that game -does- need different changes from the steam version, it has to retain it's own file inside it's own store folder ('ULWGL' being the 'store' for non-store games) so that we can maintain the changes required for that specific version of the game.

For example it's possible the standalone version of a game or obscure store version of a game might need different protonfixes from the steam version -- thus it would -not- use a symlink in that case.

**Comment by marianoag** [comment]
> No, we want a separate file for the game even if it's just a symlink pointing to the steam game id version. The reason is because in the event that that game -does- need different changes from the steam version, it has to retain it's own file

I understand that and i meant that there is a file but only if it was different, not remove it altogether.  But now that i'm thinking there's another problem: if the steam protonfix is no longer needed it would be removed, so the symlinks are now useless.

In that case i think that the steam protonfix should be a default one, and the steam protonfix be a symlink to that one, so if the steam one is no longer needed and is removed then the other stores would still symlink to the default one.

There still could be changes to a default protonfix done for steam that break the other stores, but i think it's a worth risk for not mantaining a protonfix per store.

> `#Set SteamGameId so that non-steam versions can pick up steam-specific fixes in proton's wine code util.set_environment('SteamGameId','1174180')`
> 
> Is it to possibly to add this automatically in ULWGL-Launcher this seems that could be useful for many games and wouldn't need modifying the steam protonfix.

About this could it be added to each non steam store in ULWGL-Launcher (if there's a part of the launcher in python or would it belong in Proton-GE) or is there a way to append this to a .py file instead of just symlinking?

**Comment by marianoag** [comment]
> That's not difficult. Seeing as the MRs are moderated we can just make a script to find broken symlinks and remove them, and document to run the script when removing a steam protonfix

I meant if the steam protonfix is removed, but the fixes are still needed for other stores, so instead of just removing the symlink the content of the old steam protonfix needed to be copied to the other store protonfix.

But i guess i'm thinking it wrong, after all the point of this is to have all Steam specific fixes for a game working on any store so if there's a specific fix needed for another store there would be a separate file. And if it's a symlink, any modification or being removed entirely wouldn't cause trouble for other stores.

> With these commits the SteamGameId (aka appid) should get set globally as the second part of the ulwgl id if it determines the second part of the ulwgl id is numeric. this allows both SteamAppId envvar and SteamGameId envvar to be active for proton's (and proton-wine's) usage when called on, while protonfixes still prioritizes ULWGL_ID.

Yes, i saw those commits. Now it's no longer needed to set the gameid like in the RDR2 protonfix. That's great.
