### ISSUE TITLE
Metal Gear Solid

### ISSUE THREAD

**Issue by strycore** [Open-Wine-Components/ULWGL-protonfixes#7]
Cutscenes play very slow (1~2 FPS), the game plays normally. 

Happens with all Wine/Proton versions tested.

**Comment by imLinguin** [comment]
I think the solution is to add DLL override `WINEDLLOVERRIDES=ddraw=n`

**Comment by imLinguin** [comment]
Fixed in cc0a27a21100310bc96b4d50f25949655853c815
I haven't tested if `dinput` that ships in latest version breaks anything, feel free to add necessary changes. If dinput is broken I'd suggest to add it as `dinput=n,b` for compatibility with old builds that don't ship it

**Comment by strycore** [comment]
Is keeping compatibility with older builds kinda pointless when we're shipping Protonfixes with Proton itself? Usage of Protonfixes requires staying on the very lastest version at any time.

**Comment by imLinguin** [comment]
I meant the game build. When you compare GOG builds https://www.gogdb.org/product/1771973390#builds
the latest one introduces `dinput.dll`.

I think I'll add dinput override for now, we'll see if any issues appear
